Adding shortcut to submit modal input on enter key
multihack/multihack-web pull request #51
Opened 2017-08-09 17:26 UTC by Right2Drive

2017-08-09 17:27 UTC, Right2Drive commented
Seems it was already failing the tests, as there are two area's it is not following your linter. Also I'm not totally sure how to run it to verify that it is working as I expect, if you could point me in the right direction I would appreciate it

2017-08-09 20:15 UTC, t-mullen requested changes
Looks good, thanks! Selector is missing a dot, but works other than that.

2017-08-09 20:15 UTC, RationalCoding commented on src/interface/modal.js
> +  var ip = Array.prototype.slice.call(self.el.querySelectorAll('modal-input'))
The selector needs to be `.modal-input`

2017-08-10 00:25 UTC, Right2Drive commented
Lmao my bad, I'll fix that right away :p

2017-08-10 01:11 UTC, t-mullen approved these changes

2017-08-10 01:11 UTC, merged